---

- block:

  - name: mkdir ark
    file:
      path: "/home/astel/docker-compose/ark"
      state: directory

  - name: copy docker-compose.yml
    copy:
      src: "docker-compose.yml"
      dest: "/home/astel/docker-compose/ark/docker-compose.yml"

  - name: copy env
    copy:
      src: "env"
      dest: "/home/astel/docker-compose/ark/.env"
    register: result

  - name: docker-compose up
    docker_compose:
      project_src: "/home/astel/docker-compose/ark"

  become: false

- name: firewalld ark 27015/udp
  firewalld:
    port: 27015/udp
    permanent: true
    state: enabled
    immediate: true

- name: firewalld ark 10625/udp
  firewalld:
    port: 10625/udp
    permanent: true
    state: enabled
    immediate: true

- name: copy backup.sh
  copy:
    src: ark_backup.sh
    dest: /opt/ark_backup.sh
    owner: astel
    group: astel
    mode: 0755

- name: cron ark backup
  cron:
    name: "ark backup"
    minute: "0"
    hour: "*/6"
    job: "/opt/ark_backup.sh"
  become: false

#cat /etc/arkmanager/instances/main.cfg
## Config root directory
#arkserverroot="/ark/server"
#ark_bRawSockets=""
#arkflag_crossplay=""
