#!/bin/bash


if [ -z "$1" ]; then
  user=`whoami`
else
  user=$1
fi

if [ $user == "root" ]; then
  option="-k"
else
  option=""
fi

if [ `uname -a | grep Mac | wc -l` == 1 ]; then
  host="m"
else
  if [ `ip a | grep 192.168.0.37 | wc -l` == 1 ]; then
    host="local"
  else
    host="m"
  fi
fi

cmd="ansible-playbook -i inventory/hosts -l ${host} site.yml -u $user --vault-password-file="~/ansible-pass" -v $option"

echo $cmd
eval $cmd
