---

- name: copy pi4-start-stop.sh
  copy:
    src: pi4-start-stop.sh
    dest: /opt/pi4-start-stop.sh
    mode: 0755
    owner: astel
    group: astel

- name: copy id_raspberrypi
  copy:
    src: id_raspberrypi
    dest: /home/astel/.ssh/id_raspberrypi
    owner: astel
    group: astel

- name: cron raspberry pi start
  cron:
    name: "raspberry pi start"
    minute: "0"
    hour: "9"
    job: "/opt/pi4-start-stop.sh start"
    user: "astel"

- name: cron raspberry pi stop
  cron:
    name: "raspberry pi stop"
    minute: "0"
    hour: "18"
    job: "/opt/pi4-start-stop.sh stop"
    user: "astel"
