---

- name: install elfutils-libelf-devel
  dnf:
    name: elfutils-libelf-devel

- name: check 99-pt3.rules install
  command: ls /etc/udev/rules.d/
  register: bin
  changed_when: bin.rc == 1
  failed_when: bin == 1

- block:
  - name: wget master.zip
    get_url:
      url: https://github.com/m-tsudo/pt3/archive/master.zip
      dest: "/usr/local/archive.zip"

  - name: unzip archive.zip
    unarchive:
      src: "/usr/local/archive.zip"
      dest: "/usr/local"
      remote_src: yes

  - name: make && make install
    shell: make && make install
    args:
      chdir: "/usr/local/pt3-master"

  - name: reboot
    reboot:
  when: bin.stdout.find('99-pt3.rules') == -1
