---

- name: install zabbix-release-5.2-1.el8.noarch.rpm
  dnf:
    name: https://repo.zabbix.com/zabbix/5.2/rhel/8/x86_64/zabbix-release-5.2-1.el8.noarch.rpm

- name: gpasswd -a zabbix docker
  user:
    name: zabbix
    shell: /bin/bash
    groups: zabbix,docker
    append: yes

- name: sed zabbix-agent conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agent2.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: EOF
  with_items:
    - { regexp: '^Hostname=', line: 'Hostname={{ hostname }}' }
    - { regexp: '^Server=', line: 'Server={{ zabbix_server_ip }}' }
    - { regexp: '^ServerActive=', line: 'ServerActive={{ zabbix_server_ip }}' }
  register: zabbix_agent_conf_result

- name: systemctl start zabbix-agent2
  systemd:
    name: zabbix-agent2
    state: started
    enabled: yes

- name: systemctl restart zabbix-agent2
  systemd:
    name: zabbix-agent2
    state: restarted
  when: zabbix_agent_conf_result is changed
