version: '3.8'
services:
  ark:
    image: turzam/ark
    ports:
      - "10625:10625/udp"
      - "27015:27015/udp"
    restart: always
    volumes:
      - ./data:/ark
    environment:
      SESSIONNAME: astel_ark_docker
      ADMINPASSWORD: ${ADMINPASSWORD}
      SERVERPASSWORD: ${SERVERPASSWORD}
      STEAMPORT: 10626
      SERVERMAP: "TheIsland"
      TZ: Asia/Tokyo
