---


- block:
  - name: mkdir docker-compose dir
    file:
      path: "/home/astel/docker-compose/{{ item }}"
      state: directory
    with_items: "{{ bot_names }}"

  - name: copy docker-compose.yml
    copy:
      src: "{{ item }}-docker-compose.yml"
      dest: "/home/astel/docker-compose/{{ item }}/docker-compose.yml"
    with_items: "{{ bot_names }}"

  - name: copy env
    copy:
      src: "{{ item }}-env"
      dest: "/home/astel/docker-compose/{{ item }}/.env"
    with_items: "{{ bot_names }}"

  - name: mkdir astelbot-discord mysql dir
    file:
      path: "/home/astel/docker-compose/astelbot-discord/mysql"
      state: directory

  - name: copy init mysql sql
    copy:
      src: astelbot-discord-discord.sql
      dest: /home/astel/docker-compose/astelbot-discord/mysql/discord.sql

  - name: docker-compose up
    docker_compose:
      project_src: "/home/astel/docker-compose/{{ item }}"
    with_items: "{{ bot_names }}"

  - name: cron restart discord-app
    cron:
      name: "restart {{ item }}"
      minute: "0"
      hour: "6"
      job: "cd /home/astel/docker-compose/{{ item }} && /usr/local/bin/docker-compose restart"
    with_items: "{{ bot_names }}"
  become: false
